/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Folder } from "./Folder";
import { FolderCountArgs } from "./FolderCountArgs";
import { FolderFindManyArgs } from "./FolderFindManyArgs";
import { FolderFindUniqueArgs } from "./FolderFindUniqueArgs";
import { DeleteFolderArgs } from "./DeleteFolderArgs";
import { FolderService } from "../folder.service";
@graphql.Resolver(() => Folder)
export class FolderResolverBase {
  constructor(protected readonly service: FolderService) {}

  async _foldersMeta(
    @graphql.Args() args: FolderCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Folder])
  async folders(@graphql.Args() args: FolderFindManyArgs): Promise<Folder[]> {
    return this.service.folders(args);
  }

  @graphql.Query(() => Folder, { nullable: true })
  async folder(
    @graphql.Args() args: FolderFindUniqueArgs
  ): Promise<Folder | null> {
    const result = await this.service.folder(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Folder)
  async deleteFolder(
    @graphql.Args() args: DeleteFolderArgs
  ): Promise<Folder | null> {
    try {
      return await this.service.deleteFolder(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
